[project]
name = "employee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
